version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watering-app
    ports:
      - 8081:8081
    volumes:
      - .:/source
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    command: python app.py
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: